mongo:
    image: 'mongo:latest'
    restart: always
    ports:
        - '27017:27017'
    volumes:
        - './docker/services/data/db:/data/db'
redis:
    image: 'redis:latest'
    restart: always
    ports:
        - '6379:6379'
    volumes:
        - './docker/services/data/cache:/data'
