version: '3.7'
services:
    mongo:
        image: 'mongo:latest'
        restart: always
        ports:
            - '27017:27017'
        volumes:
            - './services/data/db:/data/db'
    redis:
        image: 'redis:latest'
        restart: always
        ports:
            - '6379:6379'
        volumes:
            - './services/data/cache:/data'
    cassandra:
        image: 'cassandra:latest'
        restart: always
        ports:
            - '9042:9042'
        volumes:
            - './services/data/cassandra:/var/lib/cassandra'
