name: Continuous Deployment

on:
    push:
        branches:
            - develop
            - master

jobs:
    build:
        name: Build and Publish
        strategy:
            matrix:
                os: [ubuntu-latest]
                node-version: [12.x]
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - name: npm install
              run: |
                  npm ci
                  npm run bootstrap
              env:
                  CI: true
            - name: npm test and build
              run: |
                  npx jest --detectOpenHandles --forceExit --no-cache
                  npm run build
              env:
                  CI: true
                  NODE_ENV: production
            - name: Publish NPM Packages
              run: |
                  echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > .npmrc
                  echo "registry=https://npm.pkg.github.com/${{ github.repository_owner }}" >> .npmrc
                  npx lerna publish from-package --yes --registry="https://npm.pkg.github.com/${{ github.repository_owner }} --canary --preid dev"
                  echo "Updating package-lock.json..."

                  # Sleep for 5 seconds to hopefully give NPM time to update the package listing
                  sleep 5
                  cd ./src/aux-server

                  for i in {1..5}; do 
                      npm install --package-lock-only && break || sleep 5;
                  done
              env:
                  CI: true
            # TODO: Enable when we have proper tagging of docker releases
            - name: Get Git tag
              id: gittag
              uses: WyriHaximus/github-action-next-semvers@v0.1.0
              env:
                  GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
            - name: Build and Publish aux
              uses: mattdavis0351/actions/docker-gpr@v1
              with:
                  repo-token: ${{ secrets.GITHUB_TOKEN }}
                  image-name: aux
                  dockerfile-location: ${{ github.workspace }}/Dockerfile
            - name: Build and Publish aux-proxy
              uses: mattdavis0351/actions/docker-gpr@v1
              with:
                  repo-token: ${{ secrets.GITHUB_TOKEN }}
                  image-name: aux
                  dockerfile-location: ${{ github.workspace }}/src/aux-proxy/Dockerfile
            - name: Build and Publish aux-redirector
              uses: mattdavis0351/actions/docker-gpr@v1
              with:
                  repo-token: ${{ secrets.GITHUB_TOKEN }}
                  image-name: aux
                  dockerfile-location: ${{ github.workspace }}/src/aux-redirector
    # TODO: Enable this when the Docs should be built from GitHub instead
    #       of Jenkins
    # docs:
    #     name: Build Docs
    #     strategy:
    #         matrix:
    #             os: [ubuntu-latest, macOS-latest, windows-latest]
    #             node-version: [12.x]
    #     runs-on: ${{ matrix.os }}
    #     steps:
    #         - uses: actions/checkout@v1
    #         - name: Use Node.js ${{ matrix.node-version }}
    #           uses: actions/setup-node@v1
    #           with:
    #               node-version: ${{ matrix.node-version }}
    #         - name: yarn install and build docs
    #           run: |
    #               cd docs
    #               yarn
    #               yarn build
    #           env:
    #               CI: true
