name: Continuous Integration

on: [push, pull_request]

jobs:
    test:
        name: Test
        strategy:
            matrix:
                os: [ubuntu-latest, macOS-latest]
                node-version: [12.x, 13.x]
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - name: npm install and test
              run: |
                  npm ci
                  npm run bootstrap
                  npx jest --detectOpenHandles --forceExit --no-cache
              env:
                  CI: true
    build:
        name: Build
        strategy:
            matrix:
                os: [ubuntu-latest, macOS-latest]
                node-version: [10.x, 12.x]
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - name: npm install and build
              run: |
                  npm ci
                  npm run bootstrap
                  npm run build
              env:
                  CI: true
